In [2]:
pip install opencv-python

  Obtaining dependency information for opencv-python from https://files.pythonhosted.org/packages/c7/ec/9dabb6a9abfdebb3c45b0cc52dec901caafef2b2c7e7d6a839ed86d81e91/opencv_python-4.9.0.80-cp37-abi3-win_amd64.whl.metadata
   ---------------------------------------- 0.0/38.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/38.6 MB 3.6 MB/s eta 0:00:11
   ---------------------------------------- 0.2/38.6 MB 2.1 MB/s eta 0:00:19
   ---------------------------------------- 0.3/38.6 MB 2.5 MB/s eta 0:00:16
   ---------------------------------------- 0.5/38.6 MB 2.8 MB/s eta 0:00:14
    --------------------------------------- 0.6/38.6 MB 2.9 MB/s eta 0:00:14
    --------------------------------------- 0.7/38.6 MB 3.1 MB/s eta 0:00:13
    --------------------------------------- 0.8/38.6 MB 3.2 MB/s eta 0:00:12
   - -------------------------------------- 1.0/38.6 MB 3.2 MB/s eta 0:00:12
   - -------------------------------------- 1.1/38.6 MB 3.0 MB/s eta 0:00:13
   - -----------

# Import image using python

In [1]:
import cv2

In [2]:
import numpy as np

In [3]:
universe=cv2.imread("C:/Users/SN56.CSE2-25/Downloads/galaxy.jpg")

In [4]:
universe

array([[[22, 12, 18],
        [32, 22, 28],
        [23, 13, 19],
        ...,
        [21, 16, 17],
        [22, 17, 18],
        [25, 20, 21]],

       [[34, 24, 30],
        [24, 14, 20],
        [20, 10, 16],
        ...,
        [18, 13, 14],
        [18, 13, 14],
        [19, 14, 15]],

       [[34, 27, 32],
        [26, 19, 24],
        [23, 16, 21],
        ...,
        [27, 21, 22],
        [26, 20, 21],
        [23, 17, 18]],

       ...,

       [[13, 29, 35],
        [38, 54, 60],
        [53, 69, 75],
        ...,
        [15, 15, 29],
        [ 3,  3, 17],
        [ 5,  5, 19]],

       [[30, 46, 52],
        [40, 56, 62],
        [44, 60, 66],
        ...,
        [16, 14, 26],
        [ 3,  1, 13],
        [ 5,  3, 15]],

       [[25, 41, 47],
        [20, 36, 42],
        [31, 47, 53],
        ...,
        [12, 10, 22],
        [10,  8, 20],
        [ 4,  2, 14]]], dtype=uint8)

In [5]:
dark=cv2.imread("C:/Users/SN56.CSE2-25/Downloads/neon wallpaper.jpg")

In [6]:
dark

array([[[65, 45, 28],
        [65, 45, 28],
        [65, 45, 28],
        ...,
        [65, 44, 29],
        [65, 45, 28],
        [65, 45, 28]],

       [[65, 44, 29],
        [65, 44, 29],
        [65, 44, 29],
        ...,
        [65, 44, 29],
        [65, 44, 29],
        [65, 44, 29]],

       [[65, 43, 31],
        [65, 43, 31],
        [65, 43, 31],
        ...,
        [65, 43, 31],
        [65, 44, 29],
        [65, 44, 29]],

       ...,

       [[15,  5, 35],
        [15,  5, 35],
        [15,  5, 35],
        ...,
        [13,  5, 35],
        [13,  5, 35],
        [13,  5, 35]],

       [[15,  5, 35],
        [15,  5, 35],
        [15,  5, 35],
        ...,
        [12,  4, 34],
        [12,  4, 34],
        [12,  4, 34]],

       [[15,  5, 35],
        [15,  5, 35],
        [15,  5, 35],
        ...,
        [12,  4, 34],
        [12,  4, 34],
        [12,  4, 34]]], dtype=uint8)

In [7]:
work=cv2.imread("C:/Users/SN56.CSE2-25/Downloads/work.jpg")

In [8]:
work

array([[[17, 17, 17],
        [17, 17, 17],
        [17, 17, 17],
        ...,
        [19, 19, 19],
        [19, 19, 19],
        [19, 19, 19]],

       [[17, 17, 17],
        [17, 17, 17],
        [17, 17, 17],
        ...,
        [19, 19, 19],
        [19, 19, 19],
        [19, 19, 19]],

       [[17, 17, 17],
        [17, 17, 17],
        [17, 17, 17],
        ...,
        [19, 19, 19],
        [19, 19, 19],
        [19, 19, 19]],

       ...,

       [[18, 18, 18],
        [18, 18, 18],
        [18, 18, 18],
        ...,
        [60, 62, 62],
        [61, 63, 63],
        [61, 63, 63]],

       [[18, 18, 18],
        [18, 18, 18],
        [18, 18, 18],
        ...,
        [59, 61, 61],
        [60, 62, 62],
        [60, 62, 62]],

       [[18, 18, 18],
        [18, 18, 18],
        [18, 18, 18],
        ...,
        [59, 61, 61],
        [59, 61, 61],
        [59, 61, 61]]], dtype=uint8)

In [14]:
 cv2.imshow("w1",dark)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
cv2.imshow("w2",work)
cv2.waitKey(0)
cv2.destroyAllWindows()