In [1]:
import cv2
import numpy as np

In [2]:
im1=cv2.imread("C:/Users/SN56.CSE2-25/Downloads/galaxy.jpg")

In [3]:
im1

array([[[22, 12, 18],
        [32, 22, 28],
        [23, 13, 19],
        ...,
        [21, 16, 17],
        [22, 17, 18],
        [25, 20, 21]],

       [[34, 24, 30],
        [24, 14, 20],
        [20, 10, 16],
        ...,
        [18, 13, 14],
        [18, 13, 14],
        [19, 14, 15]],

       [[34, 27, 32],
        [26, 19, 24],
        [23, 16, 21],
        ...,
        [27, 21, 22],
        [26, 20, 21],
        [23, 17, 18]],

       ...,

       [[13, 29, 35],
        [38, 54, 60],
        [53, 69, 75],
        ...,
        [15, 15, 29],
        [ 3,  3, 17],
        [ 5,  5, 19]],

       [[30, 46, 52],
        [40, 56, 62],
        [44, 60, 66],
        ...,
        [16, 14, 26],
        [ 3,  1, 13],
        [ 5,  3, 15]],

       [[25, 41, 47],
        [20, 36, 42],
        [31, 47, 53],
        ...,
        [12, 10, 22],
        [10,  8, 20],
        [ 4,  2, 14]]], dtype=uint8)

In [4]:

shp=im1.shape
print (shp)

(1280, 980, 3)


In [5]:
height,width=im1.shape[:2]
print(height)
print(width)

1280
980


In [6]:
cent=(height/2,width/2)
cent

(640.0, 490.0)

In [7]:
rotation_matrix=cv2.getRotationMatrix2D(center=cent,angle=25,scale=0.3)

In [8]:
print(rotation_matrix)

[[ 2.71892336e-01  1.26785479e-01  4.03864020e+02]
 [-1.26785479e-01  2.71892336e-01  4.37915462e+02]]


In [9]:
rotated_im=cv2.warpAffine(src=im1,M=rotation_matrix,dsize=(width,height))

In [10]:
cv2.imshow('Orginal image',im1)
cv2.waitKey(0)
cv2.imshow('Rotated image',rotated_im)
cv2.waitKey(0)
cv2.destroyAllWindows()

# translation matrix

In [11]:
tx,ty=width/2,height/2

In [12]:
tx

490.0

In [13]:
ty

640.0

In [14]:
Translation_matrix=np.array([[2,0,tx],[1,5,ty]])

In [15]:
Translation_matrix

array([[  2.,   0., 490.],
       [  1.,   5., 640.]])

In [16]:
Trans_im=cv2.warpAffine(src=im1,M=rotation_matrix,dsize=(width,height))

In [17]:
cv2.imshow('Orginal image',im1)
cv2.waitKey(0)
cv2.imshow('Transimage',Trans_im)
cv2.waitKey(0)
cv2.destroyAllWindows()